### ISSUE TITLE
[features] colour control nodes worth considering

### ISSUE THREAD

**Issue by aurelienpierre** [hanatos/vkdt#1]
This is a list of thoughts about robust, all-purpose and usefull way to control color, worth considering adding:

_Note : [xxx] denote vectors processed element-wise_

**1. Fulcrum-based contrast**

- **By-the-book** : `[RGB] = fulcrum * ( [RGB] / fulcrum )^ contrast`
- **How it works** : the fulcrum is usually 18 % grey, but not necessarily. It does not assume bounds at 100% and pushes luminance in a perceptually uniform way around the fulcrum.
- **Problem** : it adds saturation in low-lights, sometimes in an excessive fashion.
- **Work-around** : DaVinci Resolve seems to do a weighted average between the by-the-book way in RGB, and `Y = fulcrum * ( Y / fulcrum )^contrast` in xyY (converted back to RGB). The weight parameter is user-defined.

**2. Vibrance/saturation**

- **By-the-book** : `[RGB] = Y + saturation * ( [RGB] - Y )`, Y from XYZ space
- **How it works** : pushes away colors channels from the luminance.
- **Problem** : sometimes you want to specifically resaturate low-saturation areas and not mess-up the properly saturated ones.
- **Work-around** : `[RGB]= Y + saturation * ( [RGB] - Y )^vibrance`

**3. ASC CDL**

- **By-the-book** : `[RGB] = ( [slope] * [RGB]} + [offset] )^{power}`, slope, offset and power being set for each channel
- **How it works** : defines 3 1D transfer functions allowing to set RGB channels separately, to remove parasite colour casts or define a look (colour-grading)
- **Problem** : mostly UI : 
  - does not compensate for luminance changes, so luminance and saturation are affected at once, 
   - the power parameters are inversed (increasing them in one colour actually boosts the complimentary colour),
    - you probably want an HSV/HSL/HSY interface (derived from xyY polar coordinates), but how do you translate an HSY vector to RGB gains ? (we are not converting from pixel to pixel, but from gain to gain)
- **Work around** : (see darktable colour balance)
    - (nasty) pretend the HSY input params are vectors, convert them to RGB, then normalise them with `{RGB} - Y` and pretend these are RGB params (but this assumes the RGB params are bounded, which they are not)
    - ???

**4. Colour zones**

Not yet defined. 

Something to allow sective hue/saturation/lightness shift over a specific hue/saturation/lightness range. The problem is the inputs need to be in a perceptually even space (IPT, JzAzBz, Lab), otherwise hue shifts will be steeper in blues and softer in reds. But these spaces will irremediably fuck evey attempt of blending/masking/feathering between the corrected range and the rest of the spectrum : color noise and halos.

One possible way would be to apply the transfer functions (for hue/saturation shifting) in IPT/JzAzBz/Lab, then convert the result to RGB, and blend the output with the input using a gaussian/guided/whatever filter centered on the range to edit, but in linearly scaled RGB.

Another option could be to upsample to spectral domain, for example 8 primaries, drive a factor (gain) for each primary, and see what happens.

**Comment by hanatos** [comment]
the pipeline now has modules for stupid rgb saturation (`saturate`), aces cdl (`grade`), and some hue preserving saturation. colour zones dt-style are still on the list to do, but this might warrant a separate ticket.
