### ISSUE TITLE
fix value of DateTime in the EXIF data of exported jpgs

### ISSUE THREAD

**Issue by blitzgneisserin** [hanatos/vkdt#106]
Currently, the value of the EXIF tag DateTime in exported JPEGs is wrong because it is being copied from the raw. I would like to fix this, but I am not sure how. This is what Bing Chat suggests:

1. add `-DateTime=\"$(date +'%Y:%m:%d %H:%M:%S')\"` to line 119 in o-jpg/main.c
2. add `-DateTime=\"now\"` to line 119 in o-jpg/main.c

Which possibility would work (best)?

**Comment by ptilopteri** [comment]
would you not prefer that the resulting jpg reflect the time the image was captured rather than a "processing" date/time?

**Comment by blitzgneisserin** [comment]
That's a different EXIF tag called DateTimeOriginal, that one is not supposed to be touched. At least afik.

**Comment by blitzgneisserin** [comment]
I mean the jpg should contain both dates, so some tag should be changed. I think it's also important to know when the raw was processed.

**Comment by ptilopteri** [comment]
yes, files contain four date/time instances, 
Access
Modify
Change
Birth

on a linux system, do:
    stat <filename>.jpg

stat ./VillageIdiots.jpg 
  File: ./VillageIdiots.jpg
  Size: 33359           Blocks: 72         IO Block: 4096   regular file
Device: 8,34    Inode: 357863      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/    paka)   Gid: (  100/   users)
Access: 2024-01-21 12:22:24.702044724 -0500
Modify: 2023-10-06 09:34:54.129302067 -0400
Change: 2023-10-06 09:34:54.139302010 -0400
 Birth: 2023-10-06 09:34:54.129302067 -0400

and exiftool will show:
File Modification Date/Time     : 2023:10:06 09:34:54-04:00
File Access Date/Time           : 2024:01:21 12:22:24-05:00
File Inode Change Date/Time     : 2023:10:06 09:34:54-04:00

**Comment by hanatos** [comment]
..okay exif and file time stamps are a different thing, but i think the question is valid: why do you want to update the time stamp? this is about ModifyDate?

0x0132 	ModifyDate 	string 	IFD0 	(called DateTime by the EXIF spec.)
0x9003 	DateTimeOriginal 	string 	ExifIFD 	(date/time when original image was taken)
0x9004 	CreateDate 	string 	ExifIFD 	(called DateTimeDigitized by the EXIF spec.)

**Comment by blitzgneisserin** [comment]
You are right, DateTime only updates the file timestamp, not the Date and Time in the EXIF. ModifyDate is correct. Stupid AI.

**Comment by blitzgneisserin** [comment]
I was also a bit mislead because Media Library Assistant for Wordpress also extracts ModifyDate as DateTime, apparently there is no such tag as ModifyDate in photos, but the correct exiftool command is indeed ModifyDate.

**Comment by hanatos** [comment]
https://www.heise.de/news/Schlechte-Code-Qualitaet-durch-die-KI-Assistenten-GitHub-Copilot-und-ChatGPT-9609271.html :D

**Comment by blitzgneisserin** [comment]
So the correct fix would be `-ModifyDate=\"now\"`. This should work on all OSs, shouldn't it?

**Comment by hanatos** [comment]
did not test, but this sounds good to me.

this will work on all os that find exiftool in `/usr/bin` .. i'm kinda
sceptical this includes windows. i need to write some `basedir/` executable
search that would look for both ffmpeg and exiftool and then ship these in
the zip/appimage.

**Comment by blitzgneisserin** [comment]
I created a [pull request](https://github.com/hanatos/vkdt/pull/107) but one of the automatic checks failed. I think something is wrong with uploading the Windows build?

**Comment by hanatos** [comment]
yeah don't worry i should probably switch this upload off if it's not run
from the main repo/master branch.

merged, thanks!
