### ISSUE TITLE
cli or python to appply automatic perspective correction

### ISSUE THREAD

**Issue by arnaudocus** [hanatos/vkdt#109]
Hello ! 

I'm quite new to raw photography processing softwares and just came across darktable and vkdt. 
I see there is a CLI and also mentions to python bindings and was wondering if there was a way to process images directly using the CLI for some specific correction like automated perspective correction ?

If I understand correction you first have to use the GUI to get a config file that you could then apply using the CLI but no direct way to get everything done directly using only the CLI right ?

Many thanks !

**Comment by hanatos** [comment]
depends on what you want to achieve. vkdt cfg files are human readable/ascii, so it's simple to generate them with a text editor or an external python script, say (same format as the pst preset files). you can also pass extra config via commandline argument, after `--config`.

there is currently no algorithm within vkdt to automatically create a perspective transform from the image pixel data (it is created from a hand-drawn window).
