### ISSUE TITLE
copying EXIF does not work on Arch(-based) systems

### ISSUE THREAD

**Issue by blitzgneisserin** [hanatos/vkdt#112]
Currently, in the JPEG-export module, adding the EXIF data to the exported files only works on Debian/Fedora(-based) systems, not on Arch, because on Arch, exiftool is in a different directory.

[Here](https://github.com/hanatos/vkdt/compare/master...blitzgneisserin:vkdt:patch-3?expand=1) is a suggestion how to fix this. I don't really understand the code but it seems to work (compiled and tested).

**Comment by hanatos** [comment]
haha, love the patch. very pragmatic and unix-style. i think for portability i'll probably prefer something like the metadata expander does, i.e. read the command from config.rc https://github.com/hanatos/vkdt/blob/master/src/gui/render_lighttable.cc#L753 and maybe with some mechanism that fills dt_pipe.basedir (so that appimages/windows packages could ship exiftool and say ffmpeg in a known location).

**Comment by blitzgneisserin** [comment]
Yea I know that there is probably a better fix. But until there is one this is more functional than the current code.
Should I clean it up a bit (remove/change comments) and create a pull request?
At the moment your suggestion does not sound doable for me, not even with the help of Bing copilot.
Well at least this was an interesting experiment with GPT, I must say by far the most wow AI-experience...
Btw, no problems with compiling on Garuda Linux, which is more or less Arch.

**Comment by hanatos** [comment]
please don't put copilot code into production.. i can prepare a patch.

**Comment by blitzgneisserin** [comment]
Never mind, it's not so important, I'm just playing around. Btw, I think it found a solution for Windows and Appimages, but I can't test it.

**Comment by hanatos** [comment]
now shipping exiftool for windows and using a trampoline script next to the vkdt binary to find the system installation of exiftool.

**Comment by blitzgneisserin** [comment]
Tested and functional. Thanks. This was kinda funny though.
