### ISSUE TITLE
Distro-installed libavcodec-dev apparently not compatible

### ISSUE THREAD

**Issue by butcherg** [hanatos/vkdt#113]
Went to update master and recompile, got this:

```
gcc -Wall -pipe -I. -D_GNU_SOURCE -std=c11 -Ipipe -I. -fPIC -w -pipe -O3 -march=native -DNDEBUG  -I/usr/include/x86_64-linux-gnu -shared pipe/modules/i-vid/main.c  -o pipe/modules/i-vid/libi-vid.so  -s -lavformat -lavcodec
pipe/modules/i-vid/main.c: In function ‘modify_roi_out’:
pipe/modules/i-vid/main.c:437:42: error: ‘AVCodecContext’ has no member named ‘ch_layout’; did you mean ‘channel_layout’?
  437 |     .snd_channels   = d->actx ? d->actx->ch_layout.nb_channels : 0,
      |                                          ^~~~~~~~~
      |                                          channel_layout
pipe/modules/i-vid/main.c: In function ‘read_source’:
pipe/modules/i-vid/main.c:474:42: error: ‘AVCodecContext’ has no member named ‘frame_num’; did you mean ‘frame_number’?
  474 |     if(mod->graph->frame + 1 != d->vctx->frame_num) // zero vs 1 based
      |                                          ^~~~~~~~~
      |                                          frame_number
pipe/modules/i-vid/main.c: In function ‘audio’:
pipe/modules/i-vid/main.c:605:29: error: ‘AVCodecContext’ has no member named ‘ch_layout’; did you mean ‘channel_layout’?
  605 |     int channels = d->actx->ch_layout.nb_channels;
      |                             ^~~~~~~~~
      |                             channel_layout
make[2]: *** [Makefile:164: pipe/modules/i-vid/libi-vid.so] Error 1
```
My Ubuntu Ubuntu 22.04.3 LTS libavcodec is this:

```
glenn@bena:~/ImageStuff/vkdt-new/bin$ apt list --installed |grep libavcodec
libavcodec-dev/jammy-updates,jammy-security,now 7:4.4.2-0ubuntu0.22.04.1 amd64 [installed]
```
I haven't picked at libavcodec to see where they changed the member names of AVCodecContext, but it's likely to require some extraordinary effort to get the right package for Ubuntu 22.04 to compile vkdt.

Might want to consider a comprehensive dependencies list for the build instructions in the README.

**Comment by ptilopteri** [comment]
* Glenn Butcher ***@***.***> [02-01-24 10:24]:
> Went to update master and recompile, got this:
> 
> ```
> gcc -Wall -pipe -I. -D_GNU_SOURCE -std=c11 -Ipipe -I. -fPIC -w -pipe -O3 -march=native -DNDEBUG  -I/usr/include/x86_64-linux-gnu -shared pipe/modules/i-vid/main.c  -o pipe/modules/i-vid/libi-vid.so  -s -lavformat -lavcodec
> pipe/modules/i-vid/main.c: In function ‘modify_roi_out’:
> pipe/modules/i-vid/main.c:437:42: error: ‘AVCodecContext’ has no member named ‘ch_layout’; did you mean ‘channel_layout’?
>   437 |     .snd_channels   = d->actx ? d->actx->ch_layout.nb_channels : 0,
>       |                                          ^~~~~~~~~
>       |                                          channel_layout
> pipe/modules/i-vid/main.c: In function ‘read_source’:
> pipe/modules/i-vid/main.c:474:42: error: ‘AVCodecContext’ has no member named ‘frame_num’; did you mean ‘frame_number’?
>   474 |     if(mod->graph->frame + 1 != d->vctx->frame_num) // zero vs 1 based
>       |                                          ^~~~~~~~~
>       |                                          frame_number
> pipe/modules/i-vid/main.c: In function ‘audio’:
> pipe/modules/i-vid/main.c:605:29: error: ‘AVCodecContext’ has no member named ‘ch_layout’; did you mean ‘channel_layout’?
>   605 |     int channels = d->actx->ch_layout.nb_channels;
>       |                             ^~~~~~~~~
>       |                             channel_layout
> make[2]: *** [Makefile:164: pipe/modules/i-vid/libi-vid.so] Error 1
> ```
> My Ubuntu 22.04 libavcodec is this:
> 
> ```
> ***@***.***:~/ImageStuff/vkdt-new/bin$ apt list --installed |grep libavcodec
> libavcodec-dev/jammy-updates,jammy-security,now 7:4.4.2-0ubuntu0.22.04.1 amd64 [installed]
> ```
> I haven't picked at libavcodec to see where they changed the member names of AVCodecContext, but it's likely to require some extraordinary effort to get the right package for Ubuntu 22.04 to compile vkdt.
> 
> Might want to consider a comprehensive dependencies list for the build instructions in the README.
> 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/hanatos/vkdt/issues/113
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>

on opensuse tumbleweed, I had to add:
  fmpeg-6-libavformat-devel-6.1.1-1699.3.pm.8.x86_64 
  ffmpeg-6-libswresample-devel-6.1.1-1699.3.pm.8.x86_64 
  ffmpeg-6-libavutil-devel-6.1.1-1699.3.pm.8.x86_64 
  ffmpeg-6-libavcodec-devel-6.1.1-1699.3.pm.8.x86_64 

to support video capabilities just added to vkdt
  
-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by butcherg** [comment]
That's what I'm afraid of, libavcodec 6.1.  Ubuntu 23 is only 5, so now I have to go git-blame libavcodec to find out where the struct changes were made, so I can decide which distro-upgrade hell to take on...

**Comment by hanatos** [comment]
.. the github runners are also stuck on ubuntu 22.04, so what i do to compile the nightly packages is install a ppa:
https://github.com/hanatos/vkdt/blob/master/.github/workflows/nightly.yml#L43

**Comment by butcherg** [comment]
Ah, forgot about disable, video isn't on my dance card so that's what I'll do.

Still think a dependencies list would be good, but I'll close this particular issue.
