### ISSUE TITLE
Ubuntu 22.04: graph does not contain a display:main node!

### ISSUE THREAD

**Issue by blitzgneisserin** [hanatos/vkdt#115]
The nightly appimage does not seem to be functional on (k)Ubuntu 22.04. The program starts, and the thumbnails are visible, but when I try to open a raw by clicking on a thumbnail, the preview window is dark and and in the top left corner I see the text "graph does not contain a display:main node!"

```
anna@anna-MS-7C96:~/Downloads$ ./vkdt-0.7.99-268-g7d7474dc-x86_64.AppImage
[ERR] /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /tmp/.mount_vkdt-0e9XT8u/usr/lib/vkdt/modules/i-raw/libi-raw.so)
[gui] glfwGetVersionString() : 3.4.0 Wayland X11 GLX Null EGL OSMesa monotonic
[gui] monitor [0] HDMI-0 at 0 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_xcb_surface
[gui] no joysticks found
[gui] no display profile file display.HDMI-0, using sRGB!
[gui] no display profile file display.HDMI-0, using sRGB!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
[ERR] module o-bc1 main connector input has uninited size!
```

Graphics card is Nvidia 1660 Super. Kubuntu was installed a few weeks ago. 

Also worth mentioning that the last stable release 0.7.0 (appimage) is functional and I think the nightly was also functional like 2 weeks ago.

**Comment by hanatos** [comment]
thanks for reporting. i mean i could probably include the libstdc++ library that is used by the github worker to build the package.. but what puzzles me is that this is actually ubuntu 22.04 too. which system is yours? did you do an `apt update && apt dist-upgrade` cycle recently or is that a completely vanilla 4yo install? does it have libstdc++.so.6? what does `dpkg -l libstdc++6` say (i.e. which version is it)?

**Comment by blitzgneisserin** [comment]
```
Gewünscht=Unbekannt/Installieren/R=Entfernen/P=Vollständig Löschen/Halten
| Status=Nicht/Installiert/Config/U=Entpackt/halb konFiguriert/
         Halb installiert/Trigger erWartet/Trigger anhängig
|/ Fehler?=(kein)/R=Neuinstallation notwendig (Status, Fehler: GROSS=schlecht)
||/ Name             Version               Architektur  Beschreibung
+++-================-=====================-============-=================================
ii  libstdc++6:amd64 12.3.0-1ubuntu1~22.04 amd64        GNU Standard C++ Library v3
ii  libstdc++6:i386  12.3.0-1ubuntu1~22.04 i386         GNU Standard C++ Library v3

```

System is up to date.

**Comment by blitzgneisserin** [comment]
Now it crashes at start:

anna@anna-MS-7C96:~/Downloads$ ./vkdt-0.7.99-270-geddee50c-x86_64.AppImage
[```
gui] glfwGetVersionString() : 3.4.0 Wayland X11 GLX Null EGL OSMesa monotonic
[gui] monitor [0] HDMI-0 at 0 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_xcb_surface
[gui] no joysticks found
/tmp/.mount_vkdt-0Raz59W/usr/bin/vkdt: symbol lookup error: /tmp/.mount_vkdt-0Raz59W/usr/lib/vkdt/modules/i-raw/libi-raw.so: undefined symbol: omp_set_max_active_levels

```

Should I do more tests? I could e.g. install Lubuntu 22.04 on an external ssd.

**Comment by blitzgneisserin** [comment]
Never mind. I found the solution: I upgraded libstdc++6 from a ppa. Please reverse that gcc commit, the previous version works fine.

**Comment by hanatos** [comment]
hm not optimal. the only guess i have is that the ffmpeg6 ppa pulled in the newer libstdc++. i mean at any rate this is a transient problem with oldish distributions and will hopefully go away in april.. but thanks for doing all these tests, will revert to clang in this case.

**Comment by blitzgneisserin** [comment]
I also checked with KDE Neon Unstable which I happen to have installed on my external SSD and it's the same problem.

I'm not sure how long I will use Kubuntu 22.04. I like the old Breeze theme for Plasma that it uses...

**Comment by hanatos** [comment]
i uploaded a new nightly appimage without the ffmpeg6 ppa, with only vanilla ubuntu 22.04 packages (and without video support). could you try if that works please?

**Comment by blitzgneisserin** [comment]
Bit patience please. Turns out, I cannot remove the newer libstdc++6 without problems since a lot of other packages are dependent on it.
On KDE Neon Unstable the oldubuntu appimage crashes but that does not say much I think because it's unstable...
Maybe I need to install Lubuntu or so on the external drive...

**Comment by blitzgneisserin** [comment]
I was somehow able to remove the new libstdc++6 and install the old one but apparently the oldubuntu appimage does not work:

```
anna@anna-MS-7C96:~/Downloads$ ./vkdt-oldubuntu-0.7.99-273-g7f8fedad-x86_64.AppImage
[ERR] /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /tmp/.mount_vkdt-oFBjM3x/usr/lib/vkdt/modules/i-raw/libi-raw.so)
[gui] glfwGetVersionString() : 3.4.0 Wayland X11 GLX Null EGL OSMesa monotonic
[gui] monitor [0] HDMI-0 at 0 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_xcb_surface
[gui] no joysticks found
[ERR] module o-bc1 main connector input has uninited size!
```
