### ISSUE TITLE
oldubuntu appimage broken (libstdc++.so.6/GLIBCXX_3.4.32' not found)

### ISSUE THREAD

**Issue by blitzgneisserin** [hanatos/vkdt#118]
Apparently still the same issue. The new libstdc++.so.6 is still coming from somewhere.

```
anna@anna-ms7c96:~/Downloads$ ./vkdt-oldubuntu-0.7.99-289-g66f4143e-x86_64.AppImage
[ERR] /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /tmp/.mount_vkdt-ou5wPey/usr/lib/vkdt/modules/i-raw/libi-raw.so)
[gui] glfwGetVersionString() : 3.4.0 Wayland X11 GLX Null EGL OSMesa monotonic
[gui] monitor [0] HDMI-0 at 0 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_xcb_surface
[gui] no joysticks found
[gui] no display profile file display.HDMI-0, using sRGB!
[gui] no display profile file display.HDMI-0, using sRGB!
[ERR] could not open directory '(null)'!

```

Tested on Lubuntu 22.04.

**Comment by hanatos** [comment]
hm. tried to remove the `apt update` step from the build job, now it should be *ancient*. could you try again with the updated `oldubuntu` package?

**Comment by blitzgneisserin** [comment]
Yea, still the same result. Never mind. Just thought maybe completely delete the old ubuntu appimage.

**Comment by blitzgneisserin** [comment]
I will try to compile vkdt on Lubuntu 22.04 to find out which package is the evil one.

**Comment by blitzgneisserin** [comment]
@hanatos the rawler appimage seems to work on Lubuntu 22.04 without a newer libstdc++6

**Comment by hanatos** [comment]
awesome, so i'll remove the old one.

**Comment by hanatos** [comment]
closing this as "works without heavy c++ use" (use the rawler package for old ubuntu)
