### ISSUE TITLE
vkdt does not compile on Manjaro

### ISSUE THREAD

**Issue by Heddesdorfer** [hanatos/vkdt#127]
This is the log from "make -j20 debug > debug.txt"  [debug.txt](https://github.com/user-attachments/files/15826289/debug.txt)
vkdt not built, only vkdt-cli, vkdt-fit and vkdt-eval-profile

**Comment by hanatos** [comment]
interesting. obviously works here. your log doesn't even indicate that it tried to build the gui. do you have a custom config.mk? maybe something broke with the newer updates? is it a clean directory/fresh checkout? maybe bin/vkdt already exists and for odd reason has newer timestamp?

**Comment by Heddesdorfer** [comment]
I always follow these steps (I did it twice to sure):
renamed directory vkdt to vkdtold
`$ git clone https://github.com/hanatos/vkdt.git --recursive
$ cd vkdt
$ git submodule init
$ git submodule update`
copied config.mk from vkdtold/bin to vkdt/bin
$ make -j20 debug > debug.txt
all other known dependencies are installed.

[config.mk.txt](https://github.com/user-attachments/files/15859446/config.mk.txt)
(added ".txt" to config, otherwise it couldn't be uploaded)

**Comment by hanatos** [comment]
hm okay sounds sane. could you try *without* your old config.mk? things
moved a bit lately. you don't need a recursive checkout any more, there are
no submodules (so these commands can go, too). also if you're configured
with rawler you don't need to set the pugixml things in the config.

**Comment by Heddesdorfer** [comment]
One thing I could do myself: I had to update rust from 1.78 to 1.79. But still no GUI was built.
I appended compiler logs to file and console.
[vkdt_compilation_console_log.txt](https://github.com/user-attachments/files/15872744/vkdt_compilation_console_log.txt)
[debug.txt](https://github.com/user-attachments/files/15872746/debug.txt)

**Comment by hanatos** [comment]
.. do you have the `xxd` utility? it is needed to create the gui shaders.

**Comment by Heddesdorfer** [comment]
This is a new dependency for me...
Now vkdt compiles, but crashes.
[vkdt-bt-175265.txt](https://github.com/user-attachments/files/15873031/vkdt-bt-175265.txt)

**Comment by hanatos** [comment]
okay you could try again with current master. in general these assertions are mostly validation layer complaints that are way more useful to debug with `vkdt -d qvk` because then the error message will be printed to the console. also these are very useful to debug/harden the program, and not very useful just to run it for productive use. in fact the `debug` build target introduces some extra slow checks and memory overhead..

**Comment by Heddesdorfer** [comment]
Now it works. Thank you!
