### ISSUE TITLE
crash vkdt-rawler-xorg-0.8.99-35-gb7ce8d37-x86_64.AppImage

### ISSUE THREAD

**Issue by DominiqueFrt** [hanatos/vkdt#128]
Hi,

`(process:9893): GLib-CRITICAL **: 10:22:13.650: g_file_test: assertion 'filename != NULL' failed
[gui] glfwGetVersionString() : 3.3.6 X11 GLX EGL OSMesa clock_gettime evdev shared
[gui] monitor [0] HDMI-A-0 at 0 60
[gui] monitor [1] DisplayPort-0 at 1920 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_xcb_surface
[gui] no joysticks found
[gui] no display profile file display.HDMI-A-0, using sRGB!
[gui] no display profile file display.DisplayPort-0, using sRGB!
[ERR] ignoring old hotkeys for lighttable, sorry for the inconvenience
[ERR] ignoring old hotkeys for darkroom, sorry for the inconvenience
[ERR] ignoring old hotkeys for nodes, sorry for the inconvenience
vkdt: Aucun fichier ou dossier de ce nom.
[New LWP 9924]
[New LWP 9925]
[New LWP 9926]
[New LWP 9927]
[New LWP 9928]
[New LWP 9929]
[New LWP 9930]
[New LWP 9931]
[New LWP 9932]
[New LWP 9933]
[New LWP 9934]
[New LWP 9935]
[New LWP 9936]
[New LWP 9937]
[New LWP 9938]
[New LWP 9939]
[New LWP 9940]
[New LWP 9942]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fc39590642f in __GI___wait4 (pid=9943, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      ../sysdeps/unix/sysv/linux/wait4.c: Aucun fichier ou dossier de ce nom.
backtrace written to /tmp/vkdt-bt-9923.txt
recovery data written to /tmp/vkdt-crash-recovery.*
`
vkdt-rawler-0.8.0-x86_64.AppImage  works

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-112-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700X 8-Core Processor
Memory: 31.2 Gio of RAM
Graphics Processor: AMD Radeon RX 6600 XT

Sincerely

**Comment by hanatos** [comment]
thanks for reporting.

..did it actually write the file `backtrace written to /tmp/vkdt-bt-9923.txt`? can you attach it here?

where is the glib output coming from? how did you start the application? vkdt does not use glib.

**Comment by DominiqueFrt** [comment]
[vkdt-bt-9177.txt](https://github.com/user-attachments/files/15862545/vkdt-bt-9177.txt)
[vkdt-bt-9406.txt](https://github.com/user-attachments/files/15862547/vkdt-bt-9406.txt)
[vkdt-bt-10541.txt](https://github.com/user-attachments/files/15862636/vkdt-bt-10541.txt)


`vieux_loup@Zalman:~$ /home/Applmage/vkdt-rawler-0.8.0-x86_64.AppImage 
[gui] glfwGetVersionString() : 3.4.0 Wayland X11 GLX Null EGL OSMesa monotonic
[gui] monitor [0] HDMI-A-0 at 0 60
[gui] monitor [1] DisplayPort-0 at 1920 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_xcb_surface
[gui] no joysticks found
[gui] no display profile file display.HDMI-A-0, using sRGB!
[gui] no display profile file display.DisplayPort-0, using sRGB!
`
________________________________________________________________________

`vieux_loup@Zalman:~$ /home/Applmage/vkdt-rawler-xorg-0.8.99-35-gb7ce8d37-x86_64.AppImage 
[gui] glfwGetVersionString() : 3.3.6 X11 GLX EGL OSMesa clock_gettime evdev shared
[gui] monitor [0] HDMI-A-0 at 0 60
[gui] monitor [1] DisplayPort-0 at 1920 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_xcb_surface
[gui] no joysticks found
[gui] no display profile file display.HDMI-A-0, using sRGB!
[gui] no display profile file display.DisplayPort-0, using sRGB!
vkdt: Aucun fichier ou dossier de ce nom.
[New LWP 10542]
[New LWP 10543]
[New LWP 10544]
[New LWP 10545]
[New LWP 10546]
[New LWP 10547]
[New LWP 10548]
[New LWP 10549]
[New LWP 10550]
[New LWP 10551]
[New LWP 10552]
[New LWP 10553]
[New LWP 10554]
[New LWP 10555]
[New LWP 10556]
[New LWP 10557]
[New LWP 10558]
[New LWP 10560]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f51739a342f in __GI___wait4 (pid=10561, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      ../sysdeps/unix/sysv/linux/wait4.c: Aucun fichier ou dossier de ce nom.
backtrace written to /tmp/vkdt-bt-10541.txt
recovery data written to /tmp/vkdt-crash-recovery.*
`
___________________________________________________________________________

`vieux_loup@Zalman:~$ /home/Applmage/vkdt-rawspeed-glfw3.4-0.8.99-43-g19e803ff-x86_64.AppImage 
/tmp/.mount_vkdt-rdFR34E/usr/bin/vkdt: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_vkdt-rdFR34E/usr/bin/vkdt)
/tmp/.mount_vkdt-rdFR34E/usr/bin/vkdt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_vkdt-rdFR34E/usr/bin/vkdt)
/tmp/.mount_vkdt-rdFR34E/usr/bin/vkdt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_vkdt-rdFR34E/usr/lib/libvulkan.so.1)
`


Good reception

**Comment by DominiqueFrt** [comment]
VKDT utilise glibc_2.38. Ubuntu 22.04 utilise glibc_2.35.
Donc attendre la libération de l'upgrade ubuntu 22.04 vers 24.04

VKDT uses GLIBC_2.38. Ubuntu 22.04 uses Glibc_2.35.
So wait for the release of Ubuntu upgrade 22.04 to 24.04

`vieux_loup@Zalman:~$ /home/vieux_loup/Bureau/vkdt-rawler-glfw3.4-0.8.99-50-ge7aefb6f-x86_64.AppImage 

(process:4345): GLib-CRITICAL **: 09:48:01.640: g_file_test: assertion 'filename != NULL' failed
/tmp/.mount_vkdt-rwLKpWu/usr/bin/vkdt: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_vkdt-rwLKpWu/usr/bin/vkdt)
/tmp/.mount_vkdt-rwLKpWu/usr/bin/vkdt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_vkdt-rwLKpWu/usr/bin/vkdt)
/tmp/.mount_vkdt-rwLKpWu/usr/bin/vkdt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_vkdt-rwLKpWu/usr/lib/libvulkan.so.1)
vieux_loup@Zalman:~$ 
`
![image](https://github.com/hanatos/vkdt/assets/42612895/35386eef-3be3-4ce5-a56f-04e2dc3128dc)

**Comment by hanatos** [comment]
okay, thanks for looking it up. yes, i updated the github worker to latest ubuntu which is 24.04 nowadays (since april this year i suppose). compiling from git will still work on 22.04. are you comfortable upgrading? i suppose i can look into providing appimages for old systems (was hoping new ubuntu would come with new glfw which it didn't anyways).

**Comment by DominiqueFrt** [comment]
La libération de l'upgrade ubuntu 22.04 vers 24.04 doit arriver d'ici à fin juin avec la version 24.04.1 de Ubuntu.
The release of Ubuntu Upgrade 22.04 around 24.04 must arrive by the end of June with version 24.04.1 of Ubuntu.
J'utilise actuellement Ansel de Aurélien Pierre. Me concernant, inutile de consacrer du temps pour créer un version 22.04.applmage
Merci.
I currently use Ansel from Aurélien Pierre. Regarding me, no need to spend time to create a version 22.04. Applmage
THANKS.

**Comment by hanatos** [comment]
closing as "will fix itself as ubuntu updates"
