### ISSUE TITLE
running the graph failed (VK_TIMEOUT)!

### ISSUE THREAD

**Issue by ax006ho** [hanatos/vkdt#134]
I've tried the current version of vkdt two times:
1) from the source directory with a clean installation
2) after having installed it to the /usr/local directory
In both cases the behaviour is the same: the darkroom view comes up with the text line seen above as title.

I can switch to the lighttable view which shows the pictures in the according directory, clicking on a picture brings me back to the darkroom view with the same error messages as above

I append the log files for both cases
- [pce_stdout_master.log](https://github.com/user-attachments/files/16436360/pce_stdout_master.log) shows the compilation and execution after a fresh download
- [vkdt_stdout.log](https://github.com/user-attachments/files/16436361/vkdt_stdout.log) shows the execution from /usr/local

**Comment by ax006ho** [comment]
The version

vkdt 0.8.99-77-g07828d6d

with the packages 

mesa-vulkan-drivers.i686                      24.1.6-1.fc40
mesa-vulkan-drivers.x86_64                    24.1.6-1.fc40
vulkan-headers.noarch                         1.3.283.0-1.fc40
vulkan-loader.i686                            1.3.283.0-2.fc40
vulkan-loader.x86_64                          1.3.283.0-2.fc40
vulkan-loader-devel.x86_64                    1.3.283.0-2.fc40
vulkan-tools.x86_64                           1.3.283.0-1.fc40
vulkan-utility-libraries-devel.x86_64         1.3.283.0-1.fc40
vulkan-validation-layers.x86_64               1.3.283.0-1.fc40

works for my first tests flawlessly, so I would close this issue at the moment.

Thanks for your work on this raw photography processing workflow which sucks less!

**Comment by hanatos** [comment]
hmm glad to hear it magically fixed itself :) thanks for the update, closing this for now.

**Comment by ax006ho** [comment]
I believe that there are new vulkan packages (see above) which made the bug vanish
