### ISSUE TITLE
Check in cargo.lock files?

### ISSUE THREAD

**Issue by paperdigits** [hanatos/vkdt#136]
Hey Jo,

I'm trying to update my nixpkg for 0.8 and nixpkgs really wants a `cargo.lock` file for rawler. Can you include the lock file and perhaps make the cargo update as part of the cmake file optional so that I can turn it off when building the nixpkgs?

**Comment by hanatos** [comment]
makes sense. pushed! now it should not update to newer than in the lock file/same as on my system. let me know if the cargo update is still a problem (i left it in).
