### ISSUE TITLE
Graph Editor Issue

### ISSUE THREAD

**Issue by jedypod** [hanatos/vkdt#140]
Biggest complainer here, back with another bug report. 

Awesome to see vkdt 0.9.0 released! The zoomable graph editor is really cool. However I noticed what seems to be a bug where if you click off of the add module popup, the whole graph editor becomes unresponsive. Check this screen recording for more details:

https://github.com/user-attachments/assets/532da116-74f4-4f73-bc93-66e082f115c7

I'm on Rocky Linux 9.4, using OpenBox as my windowmanager, not using Wayland.

Hope it helps!

**Comment by hanatos** [comment]
good catch! keep them coming :)
