### ISSUE TITLE
hard to open the GUI on Windows

### ISSUE THREAD

**Issue by MrLixm** [hanatos/vkdt#141]
Hello, I am interested to have a look at vkdt for my photography workflow.
I am working on Windows 10 and tried to install the corresponding variant however it took me a lot of attempt to understand how to open the software. I tried checking for the documentation but there is no page simple as "how to open the software after installation".

Here is the steps I tried:

# steps to reproduce

## initial setup
- download 0.8.0 to F:\softwares\apps\vdkt\builds and extract here
- rename `vkdt` folder to `0.8.0`

## ❌ test1

- double click `vkdt.exe`
- the software open and close in a few seconds

## ❌ test2
- open command prompt
```shell
C:\Users\lcoll> start /B F:\softwares\apps\vdkt\builds\0.8.0\vkdt.exe
[ERR] "F:\softwares\apps\vdkt\builds\0.8.0\modules\i-jpg\libi-jpg.so": The specified module could not be found.
[ERR] "F:\softwares\apps\vdkt\builds\0.8.0\modules\i-jpglst\libi-jpglst.so": The specified module could not be found.
[ERR] "F:\softwares\apps\vdkt\builds\0.8.0\modules\i-mlv\libi-mlv.so": The specified module could not be found.
[ERR] "F:\softwares\apps\vdkt\builds\0.8.0\modules\i-vid\libi-vid.so": The specified module could not be found.
[ERR] "F:\softwares\apps\vdkt\builds\0.8.0\modules\o-jpg\libo-jpg.so": The specified module could not be found.
[ERR] "F:\softwares\apps\vdkt\builds\0.8.0\modules\o-vid\libo-vid.so": The specified module could not be found.
[gui] glfwGetVersionString() : 3.4.0 Win32 WGL Null EGL OSMesa MinGW-w64
[gui] monitor [0] Generic PnP Monitor at 0 0
[gui] monitor [1] Generic PnP Monitor at 1920 0
[gui] monitor [2] Generic PnP Monitor at 11 -1080
[gui] monitor [3] Generic PnP Monitor at -1920 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_win32_surface
[gui] no joysticks found
[gui] you have more than 2 monitors attached! only the first two will be colour managed!
[gui] no display profile file display.Generic PnP Monitor, using sRGB!
[gui] no display profile file display.Generic PnP Monitor, using sRGB!
[ERR] image could not be loaded!
```
- gui flash then close

## ❌ test3

- open command prompt
```shell
C:\Users\lcoll>cd /D F:\softwares\apps\vdkt\builds\0.8.0\

F:\softwares\apps\vdkt\builds\0.8.0>start /B vkdt.exe

F:\softwares\apps\vdkt\builds\0.8.0>[gui] glfwGetVersionString() : 3.4.0 Win32 WGL Null EGL OSMesa MinGW-w64
[gui] monitor [0] Generic PnP Monitor at 0 0
[gui] monitor [1] Generic PnP Monitor at 1920 0
[gui] monitor [2] Generic PnP Monitor at 11 -1080
[gui] monitor [3] Generic PnP Monitor at -1920 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_win32_surface
[gui] no joysticks found
[gui] you have more than 2 monitors attached! only the first two will be colour managed!
[gui] no display profile file display.Generic PnP Monitor, using sRGB!
[gui] no display profile file display.Generic PnP Monitor, using sRGB!
[ERR] image could not be loaded!
```
- gui flash then close

## ✅ test4

After checking the `--help` command I try to provide a non-empty directory
```
cd /D F:\softwares\apps\vdkt\builds\0.8.0\
start /B vkdt.exe G:\personal\photo\workspace\dcim\2024\2024_04_13_salieres\dng
```
and it finally open. Quite hard to guess the software was expecting a directory to start with !

**Comment by hanatos** [comment]
hmm thanks for reporting. i just tried 0.9.0 on a windows system. i don't know anything about windows, but just double clicking the exe worked here.

i have no idea about shells on windows (other than msys2..), but since you seem to have one open maybe you can start the exe with `./vkdt -d all` for extended diagnostics? preferably the new release or nightly version.

do you have a `Pictures` directory in your home? or maybe it is trying to read some recently used image from `/home/you/.config/vkdt/config.rc`? or  directory that was recently deleted? might be a good idea to delete any old config.rc you might have. if you find such a file, could you post it?

**Comment by MrLixm** [comment]
Hey,
I didn't think of potential issues with an old config. However even after a delete of the config in `C:\users\lcoll\vkdt` I have the same issue.
```shell
C:\Users\lcoll>cd /D F:\softwares\apps\vkdt\builds\0.9.0
F:\softwares\apps\vkdt\builds\0.9.0>.\vkdt.exe -d all
[gui] vkdt 0.9.0 (c) 2020--2024 johannes hanika
[pipe] base directory F:\softwares\apps\vkdt\builds\0.9.0
[pipe] home directory C:\Users\lcoll/vkdt/config
[pipe] loaded 84 modules
[gui] glfwGetVersionString() : 3.4.0 Win32 WGL Null EGL OSMesa MinGW-w64
[gui] monitor [0] Generic PnP Monitor at 0 0
[gui] monitor [1] Generic PnP Monitor at 1920 0
[gui] monitor [2] Generic PnP Monitor at 11 -1080
[gui] monitor [3] Generic PnP Monitor at -1920 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_win32_surface
[qvk] dev 0: vendorid 0x10de
[qvk] dev 0: NVIDIA GeForce RTX 2060 SUPER
[qvk] max number of allocations -1
[qvk] max image allocation size 32768 x 32768
[qvk] max uniform buffer range 65536
[qvk] num queue families: 5
[qvk] picked device 0 with ray tracing and with float atomics and with coopmat support
[qvk] queue 0 is idx 0 family 0
[qvk] queue 1 is idx 1 family 0
[qvk] queue 2 is idx 2 family 0
[qvk] queue 3 is idx 3 family 0
[qvk] available surface formats:
[qvk] B8G8R8A8_UNORM
[qvk] B8G8R8A8_SRGB
[qvk] R8G8B8A8_UNORM
[qvk] R8G8B8A8_SRGB
[qvk] A2B10G10R10_UNORM_PACK32
[qvk] using A2B10G10R10_UNORM_PACK32 and colour space 0
[gui] no joysticks found
[gui] you have more than 2 monitors attached! only the first two will be colour managed!
[gui] no display profile file display.Generic PnP Monitor, using sRGB!
[gui] no display profile file display.Generic PnP Monitor, using sRGB!
[qvk] available surface formats:
[qvk] B8G8R8A8_UNORM
[qvk] B8G8R8A8_SRGB
[qvk] R8G8B8A8_UNORM
[qvk] R8G8B8A8_SRGB
[qvk] A2B10G10R10_UNORM_PACK32
[qvk] using A2B10G10R10_UNORM_PACK32 and colour space 0
[db] allocating 1024.0 MB for thumbnails
[ERR] image could not be loaded!
```
I don't have a `Pictures` folder in `C:\users\lcoll` if this is what you were expecting (I moved mine)

**Comment by hanatos** [comment]
hm okay still no idea what might be going on. could you try the current nightly package? https://github.com/hanatos/vkdt/releases/download/nightly/vkdt-rawler-0.9.99-10-g4e70b061-win64.zip  at this point it doesn't contain any new features over the release, but some changed behaviour wrt file opening.

**Comment by MrLixm** [comment]
I confirm the version you sent above seems to work as expected !
Just downloaded and double clicked the exe and it worked right away.

**Comment by hanatos** [comment]
awesome, thanks for confirming. will probably roll a point release in the next couple of days (so i can start pushing feature branches to master, too..).
