### ISSUE TITLE
Wacom Tablet Drag Resets Float Slider Widget

### ISSUE THREAD

**Issue by jedypod** [hanatos/vkdt#144]
When dragging a float slider with a wacom tablet, it seems to jump to the max value of the slider and I am unable to drag. 

Here's a screenrecording to demo the issue.
https://github.com/user-attachments/assets/522393a6-8a1d-4fa2-a7da-6b93e46ab967

Let me know if I can provide any debug log or anything to help pinpoint the issue!

**Comment by hanatos** [comment]
i can confirm this on x11. it's something glfw and grabbing mouse cursors on absolute pointing devices, like https://github.com/glfw/glfw/issues/1265

i don't think there is much i can do in my side, the wacom mouse coordinates just come through as something like 100x larger than mouse pixels and create insane deltas. the good news is that this is the first issue that is specific to x11 and just works on wayland, so it seems.

**Comment by hanatos** [comment]
okay here is a possible workaround, but it's a bit ugly. commenting out like
```
// #define NK_GLFW_GL4_MOUSE_GRABBING
```
in `src/gui/nk.h` doesn't grab the mouse cursor, so slider widgets are harder to use (mouse goes out of window), but the tablet works as intended also on x11. maybe i'll have to prepare special builds for x11/pentablet support like this.

**Comment by hanatos** [comment]
(now runtime switching mouse grab, only enabled on wayland now a this seems to be an issue on windows too. no idea about macos)
