### ISSUE TITLE
Possible to create a 1.0 milestone?

### ISSUE THREAD

**Issue by WillPower3309** [hanatos/vkdt#146]
I think that having a milestone for which issues need to be solved before 1.0 is released would help potential contributors know what contributions they could make to help, and would also allow people (like myself) who have eagerly been awaiting the first big release to track what's left

**Comment by hanatos** [comment]
fair. not sure i'm as organised as this :)  there was this issue: https://github.com/hanatos/vkdt/issues/33 but i consider this done.

there's more to be done on the ray tracing/geometry front to complete the rendering/compositing package. there are only minor things i'd like to streamline for still photography workflow and maybe a few more for video. will try to put together some milestone.

**Comment by hanatos** [comment]
pretending to be organised here, but at least we have a milestone now..
