### ISSUE TITLE
vkdt doesn't react on mouse clicks

### ISSUE THREAD

**Issue by ax006ho** [hanatos/vkdt#148]
the title says all.

current vkdt version: 0.9.99-94-g90154a51

Compositor: wayland
 *-display                 
       description: VGA compatible controller
       product: Baffin [Radeon RX 550 640SP / RX 560/560X] [1002:67FF]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI] [1002]
       physical id: 0
       bus info: pci@0000:09:00.0
       version: cf
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:121 memory:e0000000-efffffff memory:f0000000-f01fffff ioport:e000(size=256) memory:fce00000-fce3ffff memory:c0000-dffff

OS: Fedora 41using the [Vulkan](https://www.khronos.org/vulkan/) graphics and compute API, installed packages:
vulkan-headers.noarch                 1.3.296.0-1.fc41 <unknown>
vulkan-loader.i686                    1.3.296.0-1.fc41 <unknown>
vulkan-loader.x86_64                  1.3.296.0-1.fc41 <unknown>
vulkan-loader-devel.x86_64            1.3.296.0-1.fc41 <unknown>
vulkan-tools.x86_64                   1.3.296.0-2.fc41 <unknown>
vulkan-utility-libraries-devel.x86_64 1.3.296.0-1.fc41 <unknown>
vulkan-validation-layers.x86_64       1.3.296.0-1.fc41 <unknown>

Is 1.3 the problem?

**Comment by hanatos** [comment]
are you using a desktop environment? which one? did you set a content scale factor? wayland and macos have this !@#$% idea that the mouse events should be scaled by some extra factor that can be set by the desktop and may or may not have anything to do with screen dpi.

vk 1.3 is okay. vkdt just doesn't ask for the newest version to give old systems a chance.

**Comment by ax006ho** [comment]
I'm using Gnome with a saling factor of 200%. Setting this to 100% makes the mouse work correctly, but I can't read any description :-(.

Is there a remedy?

**Comment by hanatos** [comment]
hm. temporary workaround might be scaling factor 100% and `fltgui/dpiscale:2` in `.config/vkdt/config.rc`. which version of glfw are you using? do you have multiple screens? the content scale factor should really be propagated through wayland->glfw->vkdt and be applied.

**Comment by hanatos** [comment]
oh one more question, on your desktop what is:
```
$ echo $XDG_SESSION_TYPE
```
?

and are you sure you run native wayland and not through xwayland? if you run `vkdt -d all` from console, what is the output?

**Comment by ax006ho** [comment]
the output from the two mentioned commands is attached.
[stdout.txt](https://github.com/user-attachments/files/17658211/stdout.txt)

**Comment by ax006ho** [comment]
the temporary workaround works, you can see the glfw version in the previous mail. 
The problem: I cannot work without scaling becase I'm using a 4K monitor and all other characters are too small for my old eyes.

I'm using a single screen.

**Comment by hanatos** [comment]
thanks for the output!

```
[gui] glfwGetVersionString() : 3.3.10 X11 GLX EGL OSMesa clock_gettime evdev shared
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_xcb_surface
```
this says that glfw is using xorg not wayland. since you're on the older glfw 3.3 there may be two distinct packages on your system, one glfw and one glfw-wayland? not sure if fedora would provide newer glfw 3.4 that has both x11 and wayland support? this one would automatically use wayland in your case, and probably avoid all the scaling issues.

(i have to say i'm really annoyed how f^&ed up the scaling is in the whole wayland ecosystem. and how all compositors, all windowing libraries, and all client applications have to contain the same hacky workarounds querying a set of environment variables and s*&t to fix it up)

**Comment by ax006ho** [comment]
Sadly to say that there is only one glfw package on Fedora systems as the attached output says
[glfw.log](https://github.com/user-attachments/files/17659496/glfw.log)

glfw 3.4 is announced for Fedora 42 :-(

**Comment by hanatos** [comment]
okay, in the mean time try this:

```
$ export XDG_SESSION_TYPE=x11
$ vkdt
```
because the envvar is straight up lying when it says `wayland` and then glfw runs xwayland.

**Comment by ax006ho** [comment]
That works perfectly, thank you very much!

**Comment by hanatos** [comment]
awesome. closing this as "completed" while we wait for wayland+friends downstream to mature and make it to packages in distros.
