### ISSUE TITLE
Git master doesn't load

### ISSUE THREAD

**Issue by prokoudine** [hanatos/vkdt#16]
Feel free to shoo me away for trying alpha software, but...

```
./vkdt /whatever/path/to/photos
[pipe] [global init] cannot open modules directory!
[gui] monitor [0] eDP-1 at 0 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_xcb_surface
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[gui] no display profile file display.eDP-1, using sRGB!
[gui] no display profile file display.eDP-1, using sRGB!
vkdt: ../ext/imgui/imgui_draw.cpp:1909: ImFont* ImFontAtlas::AddFontFromFileTTF(const char*, float, const ImFontConfig*, const ImWchar*): Assertion `(0) && "Could not load font file!"' failed.
fish: './vkdt' terminated by signal SIGABRT (Abort)
```

I'm on commit ffd4654762fb401491af9ae9d297abb7e738db3c here.

**Comment by hanatos** [comment]
oh hi alexandre and welcome :) 

looks like you're running from the `src/` directory? `vkdt` is wired for `make`ing and running from the `bin/` directory (or via global symlink say in /usr/bin but pointing to an executable in `bin/`).

i should really mv instead of cp when make is done to avoid such pitfalls.

is the intel the only GPU you have? if that is the case i fear i might have to finally look into these performance enhancements for lower end hardware..

**Comment by prokoudine** [comment]
I was running from the local /bin folder in fact :)

Yes, Intel 620 is the only thing resembling GPU that I have around.

**Comment by hanatos** [comment]
in this case, did your build finish? if it can't find the `bin/modules` or `bin/data` directory something is not quite done it seems.

do you still have a build log/output from `cd bin/ && make` ?

**Comment by hanatos** [comment]
sorry closing this for lack of information. if i had to guess i would say your glslangValidator is too old (check via `glslangValidator --help | grep vulkan1`, if it doesn't show vulkan1.2 it's too old). in this case the build process would abort before initialising all the necessary files in `bin/`.

**Comment by prokoudine** [comment]
```
glslangValidator --help | grep vulkan1
              '--client vulkan100' is the same as -V100
  --target-env {vulkan1.0 | vulkan1.1 | vulkan1.2 | opengl | 
                                     * vulkan1.0 under --client vulkan<ver>
                                     * spirv1.0  under --target-env vulkan1.0
                                     * spirv1.3  under --target-env vulkan1.1
                                     * spirv1.5  under --target-env vulkan1.2

```

**Comment by prokoudine** [comment]
The end of the build log:

```
mv abney.lut ../bin/data/
make[1]: выход из каталога «/home/alex/soft/photography/vkdt/src»
Makefile:77: [bin (src Makefile)]
mkdir -p bin/data
Makefile:13: [bin (src Makefile)]
Makefile:78: [bin (src Makefile)]
# copy so we can take the executable path via /proc/self/exe:
Makefile:79: [bin (src Makefile)]
cp -f src/vkdt-cli bin/
cp: 'src/vkdt-cli' and 'bin/vkdt-cli' are the same file
make: *** [Makefile:79: bin] Error 1
```

**Comment by hanatos** [comment]
`cp: 'src/vkdt-cli' and 'bin/vkdt-cli' are the same file`  <== that still doesn't sound like your directory structure is any closer to what it should be.

maybe try [the obs debian package?](https://software.opensuse.org/download.html?project=graphics%3Adarktable%3Amaster&package=vkdt)

in the mean time i implemented debian package conformant make file rules at top level, so you should be able to just do a usual `make && make install` in the top level source directory. it'll respect `$prefix` and `$DESTDIR` or just install system wide to `/usr` if you don't set anything explicitly.

you still might want to create `bin/config.mk` to overwrite some of the settings in `bin/config.mk.defaults`.
