### ISSUE TITLE
v4l capture fails with Marshall CV502-U3 video camera

### ISSUE THREAD

**Issue by edgecase14** [hanatos/vkdt#18]
Capture works with attached diff.

[v4l-diff.txt](https://github.com/hanatos/vkdt/files/6526388/v4l-diff.txt)

**Comment by hanatos** [comment]
hi,

thanks for this. the good news: it still seems to work with my camera.

i'm not sure i understand the patch though. you always set the io method to mmap, never to user pointer? does that work with all cameras? does it still work if you only do the G_FMT query but leave the userptr/mmap dance as it was?

**Comment by hanatos** [comment]
since there hasn't been more activity here i'm assuming it's fixed. feel free to complain if not.
