### ISSUE TITLE
assert fail QVK_MAX_SWAPCHAIN_IMAGES on Wayland

### ISSUE THREAD

**Issue by edgecase14** [hanatos/vkdt#19]
vkGetSwapchainImagesKHR(qvk.device, qvk.swap_chain, &qvk.num_swap_chain_images, NULL);
  assert(qvk.num_swap_chain_images < QVK_MAX_SWAPCHAIN_IMAGES);
  vkGetSwapchainImagesKHR(qvk.device, qvk.swap_chain, &qvk.num_swap_chain_images, qvk.swap_chain_images);

I was able to get it working changing < to <=.  my actual values were 4 <= 4

**Comment by hanatos** [comment]
great. as discussed on IRC, now we have wayland support :) (with some fullscreen quirks etc). updated the code and docs accordingly.
