### ISSUE TITLE
vulkan validation error with vulkan 1.2.198 on AMD vulkan-pro driver

### ISSUE THREAD

**Issue by da-phil** [hanatos/vkdt#27]
Using vkdt to process a RAW file on current master (e758f1be004b2745e38f86b94dca28b2dba7005e) results in the following vulkan validation error:
```
[qvk] validation layer: Validation Error: [ VUID-VkComputePipelineCreateInfo-layout-00703 ] Object 0: handle = 0x22ff760000000f24, type = VK_OBJECT_TYPE_SHADER_MODULE; Object 1: handle = 0x4e1bb10000000f23, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; | MessageID = 0xe63c2d8b | Push constant is used in VK_SHADER_STAGE_COMPUTE_BIT of VkShaderModule 0x22ff760000000f24[]. But VkPipelineLayout 0x4e1bb10000000f23[] doesn't set VK_SHADER_STAGE_COMPUTE_BIT. The Vulkan spec states: layout must be consistent with the layout of the compute shader specified in stage (https://vulkan.lunarg.com/doc/view/1.2.198.0/linux/1.2-extensions/vkspec.html#VUID-VkComputePipelineCreateInfo-layout-00703)
vkdt: qvk/qvk.c:96: VkBool32 vk_debug_callback(VkDebugUtilsMessageSeverityFlagBitsEXT, VkDebugUtilsMessageTypeFlagsEXT, const VkDebugUtilsMessengerCallbackDataEXT *, void *): Assertion `0' failed.
```

processing JPGs does not show the same behaviour, so it must be an RAW-only operation which causes the issue.

associated gdb backtrace: [vkdt-bt-236671.txt](https://github.com/hanatos/vkdt/files/7706827/vkdt-bt-236671.txt)

vulkaninfo output: [vulkaninfo.txt](https://github.com/hanatos/vkdt/files/7706831/vulkaninfo.txt)

I'm running ubuntu 20.04.3 with amdgpu 21.40.1.40501 (installed via `amdgpu-install --opencl=rocr --vulkan=pro`).

**Comment by hanatos** [comment]
/me pokes around blindly.. could you pull and try again please?

**Comment by da-phil** [comment]
YES, that was it, now I can finally open RAW files, thanks so much! :relaxed:
