### ISSUE TITLE
Preview drifts to the right on keyboard/mouse events

### ISSUE THREAD

**Issue by Lawrence37** [hanatos/vkdt#30]
Whenever I move my mouse or press a key, the preview moves to the right. It eventually drifts completely off the window and can only be recovered when the view randomly resets. Increasing the LOD reduces the distance that the preview moves per input event. Bisecting the commits reveals the issue started with ddc23798c0fce112fc7da21b1bf5d2c070ffab9e.

**Comment by hanatos** [comment]
oh thanks for bisecting directly! do you have a gamepad/joystick attached when running vkdt? the commit in question introduced gamepad navigation for zooming/panning in darkroom mode.

**Comment by Lawrence37** [comment]
No additional devices attached to my laptop. It has a touchpad and pointing stick which registers as a mouse.

**Comment by hanatos** [comment]
okay that is weird. maybe one of the two is advertised as joystick to glfw? the code really shouldn't do anything without a joystick attached. anyways, try this:

pull and rebuild, i just pushed [a small patch](https://github.com/hanatos/vkdt/commit/00a8e56c3998bf99a332c8f6054fcd584648ed4f) which:
* is more verbose about joystick usage if the `gui` debug level is active (the default)
* has an explicit 'kill switch' in `~/.config/vkdt/config.rc` if you change `gui/disable_joystick` to `0`

so if you could try and run this and report back whether it thinks there is a joystick (look for output starting with `[gui]`), and if that is the case try to disable it explicitly in the config and see if that fixes the issue?

**Comment by Lawrence37** [comment]
It does detect it as a joystick.
```
[gui] found joystick AlpsPS/2 ALPS DualPoint Stick
```
Disabling it stops the drifting.

**Comment by hanatos** [comment]
disabled it by default, so happy joystick/gamepad users have to explicitly enable it : 243c75ae

going to claim that fixes the issue.
