### ISSUE TITLE
Make it easier for end users to use fast temporal reprojection antialiasing without motion vectors

### ISSUE THREAD

**Issue by LifeIsStrange** [hanatos/vkdt#31]
Hi @hanatos :)

Your paper fast temporal reprojection without motion vectors is very interesting and solve a real problem, DLSS, XeSS and FSR 2.0 all require motion vectors which most games don't provide.
The only mainstream upscaler without motion vectors is AMD FSR 1.0, which is not temporal. Yet FSR 1.0 has become a huge sucess and is e.g. supported by most video games emulators (Yuzu (switch), RPCS3 (PS3), etc). This enables us to improve the visual quality of low polygon, old games (AKA most games that mankind has produced) and even improve the quality of recent games (e.g. Zelda Breath of the wild).
As such AMD FSR has been revolutionnary (in practice, not necessarily for scholars).
Your algorithm is the only motion vector free competitor to FSR 1.0 to my knowledge and, being temporal based, has a theoretical advantage.
Hence your algorithm, if contextually superior to FSR 1.0 would be revolutionnary for gamers arround the world !
If you think it could be competitive then the next step enabling it to become quickly mainstream in use, would be to either:
Implement it via Reshade/sweetfx https://github.com/crosire/reshade, hence enabling it for any game out of the box
or by integrating it in a console emulator such as Yuzu or RPCS3. It would BTW enable easy comparison with FSR 1.0. It might be BTW (no idea) that FSR 1.0 would be complementary and could be combined to your algorithm ? (since FSR is computationally very cheap and spatially based).
If you do this and it works, it will become instantaneously a huge success :)

**Comment by hanatos** [comment]
heya,

thanks for your enthusiasm. so far it's really just detecting something that often looks like motion vectors. the logic to merge and denoise frames is very much not core part of the paper, and i keep changing my mind about this. it also depends a lot on the context (photography, monte carlo global illumination, old game with ray traced shadows, ..?), so it's not simply an implementation issue, but depending on the use case there needs to be some specific logic how to combine the buffers you have or don't have with temporal and spatial noise reduction. i guess i'm saying at this point i certainly have no plans to implement this in third party code.

**Comment by LifeIsStrange** [comment]
Oh OK, no problem :) Plz update me if you implement it one day in third party code !
