### ISSUE TITLE
Thumbnails are not loading

### ISSUE THREAD

**Issue by ilyapopov** [hanatos/vkdt#34]
Thumbnails are not loading. If I open a directory that I have not opened before, I just see a bunch of "fly" icons (or "bomb" icons in the latest version), but the thumbnails are not showing up. If I click on an image, it opens up fine in darkroom mode. After that, a thumbnail for this particular image will appear in lighttable mode too. If I open a directory that I opened in vkdt before, thumbnails show up fine. 

I tried bisecting, and the first commit where the problem appears first seems to be 5a9ddaac16e7e9771e9bd0db1fea6a57cf962cc9

I tried running with `-d all` and in the console I see repeated messages like (this is with the latest commit 5739d25c5e582ac3f31651270514e4e5ff3e4799 )

```
[ERR] module dn2 has no connectors!
[gui] glfwGetVersionString() : 3.3.6 X11 GLX EGL OSMesa clock_gettime evdev shared
[gui] monitor [0] DisplayPort-0 at 0 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_xcb_surface
[qvk] dev 0: vendorid 0x1002
[qvk] dev 0: AMD RADV RENOIR
[qvk] max number of allocations -1
[qvk] max image allocation size 16384 x 16384
[qvk] max uniform buffer range 4294967295
[qvk] dev 1: vendorid 0x10005
[qvk] dev 1: llvmpipe (LLVM 13.0.1, 256 bits)
[qvk] max number of allocations -1
[qvk] max image allocation size 16384 x 16384
[qvk] max uniform buffer range 65536
[ERR] device does not support requested feature shaderSampledImageArrayDynamicIndexing, trying anyways
[ERR] device does not support requested feature shaderStorageImageArrayDynamicIndexing, trying anyways
[ERR] device does not support requested feature inheritedQueries, trying anyways
[qvk] picked device 0 without ray tracing support
[qvk] num queue families: 2
[qvk] available surface formats:
[qvk] B8G8R8A8_SRGB
[qvk] B8G8R8A8_UNORM
[qvk] colour space: 0
[gui] no joysticks found
[gui] no display profile file display.DisplayPort-0, using sRGB!
[gui] no display profile file display.DisplayPort-0, using sRGB!
[qvk] available surface formats:
[qvk] B8G8R8A8_SRGB
[qvk] B8G8R8A8_UNORM
[qvk] colour space: 0
[db] allocating 1024.0 MB for thumbnails
[perf] upload source total:	   0.014 ms
[perf] upload for raytrace:	   0.229 ms
[mem] images : peak rss 0.00390625 MB vmsize 0.00390625 MB
[mem] staging: peak rss 0.000244141 MB vmsize 0.000244141 MB
[perf] record cmd buffer:	   0.329 ms
[perf] i-bc1    main    :	   0.004 ms
[perf] total time:	   0.004 ms
[perf] [thm] ran graph in   0ms
[perf] upload source total:	   0.011 ms
[perf] upload for raytrace:	   0.007 ms
[mem] images : peak rss 0.00390625 MB vmsize 0.00390625 MB
[mem] staging: peak rss 0.000244141 MB vmsize 0.000244141 MB
[perf] record cmd buffer:	   0.051 ms
[perf] i-bc1    main    :	   0.003 ms
[perf] total time:	   0.003 ms
[perf] [thm] ran graph in   0ms
[ERR] could not open directory '(null)'!
[ERR] [thm] no images in list!
[qvk] available surface formats:
[qvk] B8G8R8A8_SRGB
[qvk] B8G8R8A8_UNORM
[qvk] colour space: 0
[perf] upload source total:	   0.053 ms
[perf] upload for raytrace:	   0.024 ms
[mem] images : peak rss 0.00390625 MB vmsize 0.00390625 MB
[mem] staging: peak rss 0.000244141 MB vmsize 0.000244141 MB
[perf] record cmd buffer:	   0.180 ms
[perf] i-bc1    main    :	   0.015 ms
[perf] total time:	   0.015 ms
[perf] [thm] ran graph in   0ms
[perf] upload source total:	   0.046 ms
[perf] upload for raytrace:	   0.015 ms
[mem] images : peak rss 0.00390625 MB vmsize 0.00390625 MB
[mem] staging: peak rss 0.000244141 MB vmsize 0.000244141 MB
[perf] record cmd buffer:	   0.136 ms
[perf] i-bc1    main    :	   0.013 ms
[perf] total time:	   0.013 ms
[perf] [thm] ran graph in   0ms
```
and then repeating similar messages.

**Comment by hanatos** [comment]
thanks for reporting.

how did you open the directory? from the file chooser in the gui or by passing the directory name to the command line?
(both works here)

in any case

`[ERR] could not open directory '(null)'!`

does not sound encouraging :)

anything special about your file system or directory setup? i'm calling `realpath` to resolve symlinks, maybe you're using them in a way i didn't anticipate?

the commit about timings looks very unrelated indeed. did you `make clean` recently? maybe some old residual install files/dso?

**Comment by ilyapopov** [comment]
I did `make clean` and deleted thumbnail cache and now it seems to work. 

By the way, that error about directory being null appears immediately upon opening vkdt without specifying directory on command line.

**Comment by hanatos** [comment]
hm i'm suspecting it's [this line of code](https://github.com/hanatos/vkdt/blob/master/src/gui/main.c#L214).

do you have `~/Pictures` and `$HOME` in your environment?

**Comment by ilyapopov** [comment]
The problem is actually on the next line. I was launching vkdt with `./vkdt -d all` which means `argc > 1`, and it selected the other branch. If I launch with just `./vkdt` this error message does not appear and the filename refers to `$HOME/Pictures` as expected.

**Comment by hanatos** [comment]
closing because i think it's fixed. please reopen if not.
