### ISSUE TITLE
vkdt hangs on trying to open a non existing (deleted) image from tag collection

### ISSUE THREAD

**Issue by phweyland** [hanatos/vkdt#36]
to reproduce:
- tag some images (with or without *cfg) as "x"
- delete one of these images
- go to "x" collection.
- try to open the deleted image

In darkroom_enter(), changing `char graph_cfg[PATH_MAX+100];` to  `char graph_cfg[PATH_MAX+100] = {0};` avoids hanging but the issue may be deeper.
`dt_db_load_directory()` should check if the image exists or/and when deleting the image, the corresponding symlinks should be removed.

Related somehow, deleting an image in tag collection doesn't delete the image (only the symlink).

EDIT: That's a reason to be able to get the tags per image...

**Comment by hanatos** [comment]
ah good catch. likely some realpath expansion goes wrong further down the chain. ideally we would also fix that in the innermost place, such that at least it never hangs/crashes if it is fed rubbish from the outside. i'd really like to know where it hangs. you don't happen to have a stack trace around? or else i'll reproduce on my side.

**Comment by phweyland** [comment]
Tried to reproduce the issue, but could not.
Yesterday, when I added the printf in darkroom_enter():
```
  dt_db_image_path(&vkdt.db, imgid, graph_cfg, sizeof(graph_cfg));
printf("graph_cfg %s\n", graph_cfg);
```
it crashed every time (segfault) until I initialized graph_cfg. But now it works as well. :(

**Comment by phweyland** [comment]
Trying again I get vkdt hang, but another way (it may have misled me though). To see the console's messages, I resize the vkdt window, making it hangs consistently.
Is there any gdb command I could run to get more info, at least for this case ?

**Comment by hanatos** [comment]
not sure this is a good place for generic gdb crash courses (hehe) also i use it fairly sparingly, so not the right tutor.. but:

you should probably build vkdt with `make debug` (be sure to `make clean` when changing from release to debug build, it changes sizes of structs to store stuff). also i usually run:

`gdb --args ./vkdt -d qvk`

to see all the validation layer output on the console. sometimes these hint to actual problems, they are in general very useful. sometimes newer/beta drivers have false positives.

once it hangs, you can change to the gdb window (can use `f11` in vkdt before it hangs to unfullscreen it) and use `ctrl-c` to interrupt whatever it's busy doing and then get the usual `thread apply all bt full` or whatever seems useful.

**Comment by hanatos** [comment]
oops. i think i know what's going on. thanks for the log file. will see to fix this. but it's unrelated to the tagging issue.. it's a swapchain recreation/mutex locking problem.

**Comment by hanatos** [comment]
okay i believe [this commit](https://github.com/hanatos/vkdt/commit/340c5f2e866077ffa23d9b16e3f374def882efea) should fix your deadlock issue (back to the original issue in this case..)

**Comment by phweyland** [comment]
> [this commit](https://github.com/hanatos/vkdt/commit/340c5f2e866077ffa23d9b16e3f374def882efea) should fix your deadlock issue

It does. But I had to break (ctrl-c) the build several times (no progress) to get it done. First time this happens. 

> but it's unrelated to the tagging issue.

I've tried to reproduced it but no chance. I should have been mistaken by the effect above.
I'll reopen it if necessary. Thanks.

**Comment by hanatos** [comment]
okay strange. works every time here, but also the obs seems to have
threading issues now. forced the build toolchain to single threaded now and
will think about it for a bit.
