### ISSUE TITLE
Canvas no longer updated when timelapse stops playing after last frame

### ISSUE THREAD

**Issue by qosch** [hanatos/vkdt#41]
Steps to reproduce:
- open a timelapse in the darkroom
- start playing it by clicking on "play" in the "animation" module in the "esoteric" tab
- wait for it to stop playing after reaching the last frame
- move the slider of a development module like "exposure"

Expected behavior:
- the last frame is continued to be displayed and updated as the slider is moved

Observed behavior:
- the last frame is continued to be displayed but not updated as the slider is moved

**Comment by hanatos** [comment]
my guess is that it's because the animation does not actually *stop* if you reach the last frame. i think it pretends to go on but clamps the frame to the last one. will have a look.
