### ISSUE TITLE
Do not apply llap & filmcurv when opening JPEG files

### ISSUE THREAD

**Issue by GLLM** [hanatos/vkdt#46]
Hello @hanatos,

I open this issue to keep track of my proposition, that I understand you do acknowledge to not apply RAW-dedicated modules: _llap_ & _filmcurv_ when opening JPEG files ... so that it is set out-of-the-box rather than needing the user modify the _default-darkroom.i-jpg_ and _default.i-jpg_ files.

The target is to get:
- expo: 1.0
- light: 1.0
- contrast: 1.0
- clarity: 0.0
- shadows: 1.0
- highlight: 1.0
- when opening JPEG files, in both lighttable and darkroom.

Your proposed solution: 
![image](https://user-images.githubusercontent.com/3989573/178334699-70ef9836-c6c2-4425-9a69-4b5b30c02407.png)

See: https://discuss.pixls.us/t/vkdt-dev-diary-pt2/28540/119?u=gllm

Thanks a lot,

GLLM

**Comment by hanatos** [comment]
indeed i completely forgot about this one. doing the quick fix, will do the come folder override later.
