### ISSUE TITLE
Feature request: show open directory window or open last folder when launching vkdt without parameter

### ISSUE THREAD

**Issue by GLLM** [hanatos/vkdt#47]
Hello !

When opening vkdt without parameter (neither filepath nor folderpath), could we have vkdt either showing the open directory window (usually accessible via collect > open directory menu) so that we do not need ot open the collect module, then click on open directory each & every time we open vkdt ?

Many thanks,
GLLM

**Comment by hanatos** [comment]
currently it's wired to show `~/Pictures` on startup. i think using the most recently used folder instead would be better (will do that).

note that the cascade files <-> lighttable <-> darkroom is accessible via enter (->) and escape (<-) so going from lt to files is just pressing escape once (or caps lock, for the vi users).

**Comment by hanatos** [comment]
this is now implemented and shows the most recently used folder on startup.
