### ISSUE TITLE
Preset "inpaint" should be located before "crop" in pipeline

### ISSUE THREAD

**Issue by qosch** [hanatos/vkdt#48]
Preset "inpaint" should be located before "crop" in pipeline so that changing the crop will not move inpaint spots and so that the module can use regions outside the cropped region.

**Comment by qosch** [comment]
You're right, there's another problem showing up (I'll open a new issue). Inpainting and then cropping works, cropping and then inpainting doesn't.

**Comment by hanatos** [comment]
well it's a conceptual question. in darktable there is the transform callback system that will transform individual points through the pipeline of modules thus far. it's brittle (duplicate code in processing and point transform fwd/back), slow, and not very accurate.

i'm more for a solution for grown ups:
* your graph, your responsibility to not mess with it too much
* while drawing, connect a temporary display without any transformations to help the user aim better.
* maybe disable transform modules for main display and show a local `dspy` output with transforms included

even the last points here would need some callback/infrastructure/bits to be set on transform modules (so far just `crop` and `lens` i think, maybe `resize`).

in general i'm always for the most simple workable solution. in the end that also helps the user understand what's going on.

**Comment by hanatos** [comment]
okay i think the preset should be before crop to be able to paint from outside the crop region (i buy your argument there).

wrt transforms switching off, the "temporarily switch off in gui" mode is probably what should be used here, and also for that it will need to go before the crop module. might have a convenience mode that switches off all transform modules (crop/lens) when drawing.
