### ISSUE TITLE
Bug: JPEG should be rotated based on exif info (lighttable & darkroom)

### ISSUE THREAD

**Issue by GLLM** [hanatos/vkdt#50]
Hello,

I think something should be done so that JPEG are properly rotated (according to EXIF bit) in lighttable & darkroom.
On my side, they appear un-rotated (in both modules), on pictures taken with
- Fujifilm X-T3 / X-T20
- Nikon D600 / D70 / D200 / D50
- Samsung S8+

Thanks
GLLM

**Comment by hanatos** [comment]
right. i'm not loading the exif data. like, at all, but there is an (optional) code path in the `i-raw` module only that would load it. for most intents and purposes, however, it's very much enough to get the data provided by rawspeed (maker model iso orientation).

maybe there's an un-bloaty way of reading that kind of data from jpg? if not i suppose [this code](https://github.com/hanatos/vkdt/blob/master/src/pipe/modules/i-raw/main.cc#L262) can be copied to the `i-jpg` module.

**Comment by GLLM** [comment]
Installé still crashes. Coule not test !

**Comment by hanatos** [comment]
could you post your .config/vkdt/config.rc? does it work if you give a
folder name on the commandline? did the "watch killall -15 vkdt" trick give
you a backtrace?

**Comment by GLLM** [comment]
@hanatos, sorry I could not test earlier the watch/kill.

Here's my ./config/vkdt/config.rc

```
username@computer:~$ more .config/vkdt/config.rc 
intgui/lod:1
intgui/export/wd:0
intgui/export/ht:0
intgui/export/format:0
fltgui/export/quality:90
strgui/export/basename:/tmp/img
fltgui/dpiscale:0.75
strqvk/device_name:null
intgui/ruc_num:7
strgui/ruc_entry00:/path_which_contains_space
strgui/copy_destination:${home}/Pictures/${date}_${dest}
strgui/ruc_entry01:/path_which_contains_space_2
strgui/ruc_entry02:/path_which_contains_space_3
strgui/ruc_entry03:/path_which_contains_space_4
strgui/ruc_entry04:/path_which_contains_space_5
strgui/ruc_entry05:/path_which_contains_space_6
strgui/ruc_entry06:/path_which_contains_space_7
```

and the watch killall -15 vkdt helped, as it avoided me a cold reboot.
Here's the backtrace :

```
username@computer:~$ ./vkdt/bin/vkdt
[gui] glfwGetVersionString() : 3.3.6 X11 GLX EGL OSMesa clock_gettime evdev shared
[gui] monitor [0] DP-3 at 0 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_xcb_surface
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[gui] no joysticks found
[gui] no display profile file display.DP-3, using sRGB!
[gui] no display profile file display.DP-3, using sRGB!
Terminated
```

Thanks

**Comment by hanatos** [comment]
okay, we're making progress here :)

did it write a stack trace to /tmp/vkdt-bt-* before it got terminated now?
if not, can you try sigsegfault instead? (killall -11)

the /paths_which_contain_spaces all look sane to you? not that these got
messed up for a random reason or another and then it can't open it.

**Comment by GLLM** [comment]
@hanatos,
I've finally foudn the culprit !
Mi graphic card driver had been switched from NVidia to Xorg new driver.
After switching back to Nvidia's, everything is working fine.

I'm ashamed !
Sorry
GLLM

**Comment by hanatos** [comment]
no worries and glad to hear it's working again! ideally it wouldn't hang so
badly in this case..

**Comment by GLLM** [comment]
Fix tested on a newly cloned repo (as of today 19.09.2022) : JPEGs are not rotated.
Issue reproduced for

- Fujifilm X-T3 / X-T20
- Nikon D600 / D70 / D200 / D50
- Samsung S8+

**Comment by hanatos** [comment]
you mean they should be rotated but are not? do you have existing .cfg? the
automatic exif detection will only work if you start from the defaults (no
existing .cfg) or have a virgin crop module in the pipeline (you can insert
it manually but that defeats the purpose of automatic rotation i suppose).

**Comment by GLLM** [comment]
Yep, JPEGs taken in portrait are loaded in landscape, both in lighttable & in darkroom.

**Comment by hanatos** [comment]
without existing .cfg? if you have an existing one, what happens if you
reset it it lighttable ("selected images" -> "reset history stack")?

**Comment by GLLM** [comment]
Rest history stack does not change anything.

I just noticed one thing:
Pictures never gets properly rotated were taken with
* Samsung smartphones
* Nikon DSLR

On *some* photos taken with Fuji cameras, the lighttable shows them the wrong way.
When I double-click one to open it in DR, it is rotated properly. 
Then I press escape to get back to the Lighttable and the thumbnail is updated after 1-2s and is then properly rotated/displayed.
I've yet to identify the reason why it rotates some and not the others !

**Comment by GLLM** [comment]
@hanatos

FYI/FWIW: I've seen today, that with one of your recent commit (I'm using a build based on https://github.com/hanatos/vkdt/commit/45c57d105109bd36248c392c880f121531cd33a8), the thumbnails of a folder are now turned properly *if* vkdt opens on the said folder.

This means
* all thumbnails of a folder are now rotated at once when it's the folder selected by default on open. No need to open each photo one by one so that the rotation happens
* if you open vkdt, select another folder: the rotation of not yet properly displayed thumbnails wont happen. Close vkdt & reopen it: the automated rotation of all pictures requiring it will now happen, since vkdt now has started with this folder by default.

If this may be of any value

Best,
GLLM
