### ISSUE TITLE
Bug ? Crop does allow for out of picture cropping !

### ISSUE THREAD

**Issue by GLLM** [hanatos/vkdt#52]
Crop:crop does allow for out of picture cropping :

Crop setup
![image](https://user-images.githubusercontent.com/3989573/191091281-cca5af3d-b5b5-4c45-9e2c-5048fa3eeecb.png)

Result in DR:
![image](https://user-images.githubusercontent.com/3989573/191091482-c7277be6-606f-4e8a-826a-064b517b2b6f.png)

Appears the same in lighttable
![image](https://user-images.githubusercontent.com/3989573/191091676-21739af6-bfac-4a3f-9b9d-1f9c7e3291ad.png)

Feature or bug ? I may miss a usecase I'm not aware of !

Thanks
GLLM

**Comment by hanatos** [comment]
indeed, i don't have a use case either. maybe people want to keyframe some animation where the image scrolls through or something. i mean restricting it would be more code and taking away power from the user.

but what i think we should have is an "auto-crop" button which makes sure (maybe preserving aspect ratio) that there are no black borders. especially after rotation this can be convenient.

**Comment by GLLM** [comment]
Auto-crop sounds like a nice solution, indeed.
And the preserve ratio is a nice one too, though it's better if can can be unlocked on demand.

Thanks

**Comment by GLLM** [comment]
And adding this to the straighten functionality would be nice too !

**Comment by hanatos** [comment]
.. okay i think we have `auto crop` now and i'll consider the add-black-border cropping a feature for esoteric use cases that i am yet to come up with.
