### ISSUE TITLE
Feature request : zoom % indicator in darkroom

### ISSUE THREAD

**Issue by GLLM** [hanatos/vkdt#53]
Hi Hanatos,

when zooming on my photos in DR, I always wonder how much I'm zoomed in : am I at 100% (which I usually want) or more  (sometimes OK, sometimes not) ?

Do you think adding a zoom text indicator (xyz%) somewhere in DR could be feasible ?

And if this is too much UX/UI for the moment, dont hesitate to say so :-)

Many thanks !
GLLM

**Comment by hanatos** [comment]
i think that is an easy/reasonable request and should not be much work nor bloat the code :)

**Comment by GLLM** [comment]
works fine, thanks
