### ISSUE TITLE
Bug: Thumnails have a black bar on side

### ISSUE THREAD

**Issue by GLLM** [hanatos/vkdt#54]
Hi @hanatos

I see that, with the latest CL [45c57d1](https://github.com/hanatos/vkdt/commit/45c57d105109bd36248c392c880f121531cd33a8) the thumbnails in lightroom now have a unexpected black bar, whether taken in landscape or portrait mode:

![image](https://user-images.githubusercontent.com/3989573/198088772-b98a24a2-accc-40ec-a077-fa722d7aeb4f.png)

Do you confirm this is a bug ?

Thanks
GLLM

**Comment by hanatos** [comment]
right. i think i've seen this before, but don't know where it comes from. investigating.

**Comment by GLLM** [comment]
Confirmed, issue solved with https://github.com/hanatos/vkdt/commit/910fba47aeeea055b8011c4f78e0cc46899b7c52
