### ISSUE TITLE
Feature request: enable moving to the next/previous photo of the folder in darkroom

### ISSUE THREAD

**Issue by GLLM** [hanatos/vkdt#56]
Hi,

I often want to retouch several photos in a row, and switch from one to another when doing so.
Thus, I'd liek to be able in _darkroom_ to move to the next or previous image of the folder.

Is this something you could consider ?

Thanks a lot
GLLM

**Comment by hanatos** [comment]
hi,

this is L1/L2 on the gamepad or spacebar/backspace on the keyboard. does that not work on your setup?

**Comment by GLLM** [comment]
Oh, I did not know that !
I just tried (spacebar/backspace) and it works.

Ideally, one day, keyboard shortcuts in DR will be customizable (I would use ctrl+left and ctrl+right for this usecase)

Thanks,
GLLM
