### ISSUE TITLE
[Bug] In darkroom, the overview of 'zone' module is not correctly oriented

### ISSUE THREAD

**Issue by GLLM** [hanatos/vkdt#58]
Hi,

Sorry for the flood of issues :)

Doing some exploration of modules I do not know, I opened the zone module.
And saw that the overview is not properly oriented:
![image](https://user-images.githubusercontent.com/3989573/198375069-7a328dfd-8602-4431-bb38-82e536d47989.png)

Tested on the latest CL possible

Thanks
GLLM

**Comment by hanatos** [comment]
but it is correctly oriented. it's just before `crop` (and rotate) in your pipeline.

**Comment by GLLM** [comment]
I'm noobing all I can un the pipeline thungie ... 
Sorry for the false alarm !
