### ISSUE TITLE
Feature: in darkroom, add the ability to reset the history stack of the image being processed !

### ISSUE THREAD

**Issue by GLLM** [hanatos/vkdt#59]
Hi,

yet another feature request ! :-o
In darkroom, would it be possible to have the ability to quickly reset the stack of the image being processed ?
I can do it in lighttable, but when, in DR, I messed things up in my pipeline, I need to go back in LT, make sure I'm on the right image and then use the selected images > reset history stack.

A one click action from within DR would be neat, whether in the 'Tweak all' or in the 'Pipeline config' tabs !

Thanks
GLLM

**Comment by hanatos** [comment]
![2022-10-28-165031_669x438_scrot](https://user-images.githubusercontent.com/1574185/198659000-0f472e41-d91a-4165-bec9-b9eda2e4c41c.png)

added three buttons like this^ in the left panel (open with ctrl-h by default, see keybindings table in darkroom mode).

**Comment by GLLM** [comment]
Thanks for this !!
