### ISSUE TITLE
Provide desktop file so users can open vkdt without console

### ISSUE THREAD

**Issue by qosch** [hanatos/vkdt#63]
Maybe a good idea for version 1.0 :)

**Comment by hanatos** [comment]
hah, i suppose you must be right. i remember this thing from darktable, but have no idea about it and how one would open any program without console :) cannot be hard to create such a file though.

**Comment by qosch** [comment]
Here is a link to the file darktable uses: https://github.com/darktable-org/darktable/blob/master/data/darktable.desktop.in

I guess modifying this isn't the hard part, having it copied/linked in the right folder during "installation", so the desktop environment finds it, is.

**Comment by hanatos** [comment]
for the record, this stuff seems to be required/hard to switch off for appimages, so in the [appimage creation script](https://github.com/hanatos/vkdt/blob/master/bin/mkappimg.sh) i'm using something like
```
# create fake desktop entry + icon because apparently it's needed
mkdir -p AppDir/usr/share/applications
cat > AppDir/usr/share/applications/vkdt.desktop << EOF
[Desktop Entry]
Name=vkdt
Comment=gpu accelerated photography workflow toolbox
Exec=vkdt
Icon=vkdt
Terminal=false
Type=Application
Categories=Graphics;
StartupNotify=false
EOF
mkdir -p AppDir/usr/share/icons/
cp vkdt.png AppDir/usr/share/icons/
```
(i.e. the desktop file goes to `/usr/share/applications/` and there's [some wip/standin icon too](https://vkdt.org/favicon.svg))

**Comment by hanatos** [comment]
the git version should install such a thing now.
