### ISSUE TITLE
systematic issue

### ISSUE THREAD

**Issue by cherob67** [hanatos/vkdt#65]
I have a systematic crash when i try to add a module in the pipeline config. I join the screen when i try and the different files about this crash
![vkdt_add_mod](https://user-images.githubusercontent.com/46007178/209783760-fc083527-8426-47fa-a73f-a2ff5a07bd7d.jpg)
[vkdt-bt-7690.txt](https://github.com/hanatos/vkdt/files/10313136/vkdt-bt-7690.txt)

**Comment by hanatos** [comment]
heya,

how did you build vkdt? inside the bin/ directory or top level? did you `make install`? which binary are you calling? `/usr/local/bin/vkdt` ? or inside the git directory `bin/` `./vkdt`? this dialog looks like it fails to find the module directory, which should be in the git repo as `bin/modules` or installed as `/usr/local/lib/vkdt/modules` .

**Comment by cherob67** [comment]
I don't built vkdt by myself; i use the opensuse repository. I am under ubuntu 22.04 and i run by a simple command line 'vkdt'.

**Comment by hanatos** [comment]
okay thanks will see how i can test this package and what might be happening.

**Comment by cherob67** [comment]
thanks

**Comment by hanatos** [comment]
should be fixed now, new obs packages are on the way. thanks for reporting!

**Comment by cherob67** [comment]
that's fine !
