### ISSUE TITLE
Attempt to create tag causes crash

### ISSUE THREAD

**Issue by MartinScharnke** [hanatos/vkdt#68]
Version: 0.5.0+git14.d8d8a1a-0+102.1
Platform: Linux BARADDUR 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
Vulkan Instance Version: 1.2.162
GPU id = 0 (NVIDIA GeForce GTX 1660)

To reproduce: 
Attempt to create a tag.
No additional information written to stdout when starting with -d all

Behaviour:
crash, writing a bare vkdt-bt file, containing:

this is vkdt 0.5.0+git14.d8d8a1a-0+102.1 reporting a crash:

**Comment by hanatos** [comment]
heya

there was a bug like this in some older version. the current version should be formatted more like "vkdt 0.5.9999-157-gac9dbaa6" (i think this particular hash is not on github but the "9999" part you should have too). so i wonder where you got the package from? installed from older git? does the version change if you `git pull --tags` ?

**Comment by MartinScharnke** [comment]
Thanks ... I had not updated in a couple of weeks. I don't build from source, I haven't been able to install all the dependencies in Debian.
An update  now gives a version string of

vkdt 0.5.9999+git153.409a1b1-0+103.1 (c) 2020--2023 johannes hanika 

and the tagging now works without crashes.

Sorry for the noise.

**Comment by MartinScharnke** [comment]
fixed in current version
