### ISSUE TITLE
default position of the nodes

### ISSUE THREAD

**Issue by cherob67** [hanatos/vkdt#69]
Hello, concerning the default position of the nodes, after many tries to try to understand why it didn't work for me, I managed to have the expected operation but in a particular way.
For a picture, for example Images/crw_9460.crw, I do a "reset history stack" (so the .config/vkdt/nodes/9443ce1c34a21e4d.dat and Images/crw_9460.crw.cfg files are erased). Then, I open the picture with vkdt and I open the node editor.
If the first line of the default.i-raw.dat file contains "Images/crw_9460.crw.cfg", I get the layout of the nodes corresponding to the default.i-raw.dat file. If this first line is empty or deleted or with another .cfg file or any thong else, it no longer works. I redid the test with several raw photos, it seem to be systematic. To have the correct layout of the nodes, I have to modify the first line of the default.i-raw.dat file as indicated above.
I have the same result in jpg with the default.i-jpg.dat file. I have not tried with the other (i-pfm, etc.)

**Comment by hanatos** [comment]
oooh thanks for that detailed analysis! it seems clear this cannot work :) will think of a fix.

**Comment by hanatos** [comment]
https://github.com/hanatos/vkdt/commit/e6a801f85462cea7b96b507f0a0acd60071df9b6  <= i hope this fixes it.

**Comment by cherob67** [comment]
Yes it's fixed and all works now  ! thanks
