### ISSUE TITLE
Feature: combined demosaicing and denoising

### ISSUE THREAD

**Issue by tpapp** [hanatos/vkdt#71]
Combining demosaicing and denoising is intuitively appealing, as it treats the information captured by the sensor as a noisy sample of an underlying image.

Some examples include:

- [Goossens, Bart,  et al. "An overview of state-of-the-art denoising and demosaicking  techniques: toward a unified framework for handling artifacts during  image reconstruction." Image Sensor Workshop. 2015.](https://biblio.ugent.be/publication/7199064/file/8114779)
- [FlexISP: A Flexible Camera Image Processing Framework](https://research.nvidia.com/sites/default/files/pubs/2014-12_FlexISP-A-Flexible/FlexISP.pdf)
- [Noise Suppression in Low-light Images through Joint Denoising and Demosaicing](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/267_lowlight.pdf)

I don't know enough about Vulkan to judge which of these would be feasible, but it seems that combining these two steps into a single one would result in improved reconstruction.

**Comment by hanatos** [comment]
yeah i think i know these papers and/or similar ones. it's a rathole though. i'm going to say that probably all of that is possible in vk, but i'm not sure i want to jump into it.

i haven't had much success outputting interpolated pixels from the pre-demosaic denoiser for instance. mostly there are edge cases that make custom cut code sharper for demosaicing and avoid colour artifacts better.

so i guess i'm saying: yes, probably there's something to be gained but i'll not go around actively researching literature for something here. if you have one specific paper with super convincing results and reasonably simple algorithm we can discuss though.

**Comment by hanatos** [comment]
just a quick note on this, i have a neural network that performs bayer denoising + demosaicing. the reasoning is that this is going to be expensive, so it'll have to replace as much as it can.. maybe slight sensor lowpass filter sharpening too. it's dead slow though, initial experiments are more like 70ms/24MP image. time will have to show whether this is going to be useful in practice.

**Comment by hanatos** [comment]
this is now implemented and merged to master, as the `jddcnn` module. the results are mixed, and it's certainly much slower than the conventional way of doing it. looking forward to improving the training with real data, this should be able to produce much better results. i suppose that should be a separate issue though.
