### ISSUE TITLE
Feature: use GitHub Actions to automatically generate Windows and macOS binaries 

### ISSUE THREAD

**Issue by ghost** [hanatos/vkdt#81]

**Comment by hanatos** [comment]
this is certainly not only a single feature request. if there are unobtrusive patches to support these platforms i'll merge. i seem to remember macintosh + moltenvk used to work at some point in the past.

**Comment by hanatos** [comment]
closing this as too open-ended. will refer to the existing nightly msys2 windows github action build here for the windoos part and to this pull request:

https://github.com/hanatos/vkdt/pull/87

for the macintosh part. as i don't have access to macintosh hardware i can't really work on it myself. i'm guessing the github action is not much work once the port itself works.
