### ISSUE TITLE
Q: raytracing and geo format

### ISSUE THREAD

**Issue by ib00** [hanatos/vkdt#84]
I am trying the raytracing module and want 
to create some geometry.

I have looked in corona-13, but I am still not entirely clear on the .geo input format.
Say I have two different mesh objects and a bunch of spheres and I want to write
them in a .geo format:
1) Can I have one giant array of positions and then just manipulate 'primid_t' structure?
(shapeid = 0 for mesh 1, 1 for mesh 2, 2, for sphere 1, etc., and vi be set to proper index)

**Comment by hanatos** [comment]
hi,

sorry i didn't try the geo module in the longest time.. and did some significant changes to the memory layout of the raytracing geometry + extra data during the course of working on quake. i'm sure this one will need an overhaul (best once i merge pending changes). the rest of the question probably belongs to the c13 repository. maybe this can answer some of your questions (writing out a bunch of spheres/particles): https://github.com/hanatos/corona-13/blob/master/tools/geo/obj2particles.c

closing this now, probably fixing up the `i-geo` and `rt` modules is a separate task.
