### ISSUE TITLE
[Bug][AMD] Hovering on node icons in "tweak all" tab freezes GUI

### ISSUE THREAD

**Issue by LDAP** [hanatos/vkdt#85]
**Reproduce:**

1. Open vkdt
2. Hover on any of those symbols:
![image](https://github.com/hanatos/vkdt/assets/8215084/f762ea78-f173-4f03-b6df-2a47d2950a7b)

(Same happens when hovering in "force downloading all outputs" in esoteric)

**Actual behavior**:
Swap chain is recreated a few times and the window disappears and reappears a few times.
Then the GUI is frozen.

```
[qvk] available surface formats:
[qvk] B8G8R8A8_UNORM
[qvk] B8G8R8A8_SRGB
[qvk] colour space: 0
[qvk] available surface formats:
[qvk] B8G8R8A8_UNORM
[qvk] B8G8R8A8_SRGB
[qvk] colour space: 0
[repeates a few times]
```

**Expected behavior**:
GUI stays responsive, no recreations

**Comment by hanatos** [comment]
ah, good catch. i think this has nothing to do with amd, but with imgui's multi-viewport feature (for dual screen support in this case). it creates a new viewport for tooltips.. which is a bit too much. especially for tiling window managers in non-fullscreen mode this causes very interesting loops of windows being created and destroyed. i hope forcing the tooltips to the main viewport will fix the issue.

**Comment by LDAP** [comment]
https://github.com/hanatos/vkdt/commit/98a74a39660884b0341655af5d629bb068fd3539 fixed the issue on my end :)
