### ISSUE TITLE
Suggestion for the module AB Comparison.

### ISSUE THREAD

**Issue by cherob67** [hanatos/vkdt#98]
Hello !
I would like to make a suggestion regarding the AB Comparison module that I used to visualize mask combinations. It would be interesting to add an opacity parameter (like in the blend module) on each input so as to be able, for example, to better visualize the position and appearance of the different masks in relation to each other and in relation to the processed image.

**Comment by hanatos** [comment]
you mean left/right separation as in the ab module but also opacity? i mean you could of course just replace the ab by a blend module or daisy chain blend + ab to get the desired effect if i understand that correctly?

**Comment by cherob67** [comment]
Yes ! That's right and i tried successfully the solution with blend modules. Adding opacity parameters in AB modules, if it is possible, would be more simple than adding blend modules.

**Comment by hanatos** [comment]
okay, closing this for now. sounds like a very specific workflow that could be optimised by custom presets.
