### ISSUE TITLE
Crash (Ubuntu / WSL2): yuv (G8_B8R8_2PLANE_420) not supported!

### ISSUE THREAD

**Issue by benthillerkus** [hanatos/vkdt#99]
```
[gui] glfwGetVersionString() : 3.3.6 X11 GLX EGL OSMesa clock_gettime evdev shared
[gui] monitor [0] XWAYLAND0 at 0 0
[gui] vk extension required by GLFW:
[gui]   VK_KHR_surface
[gui]   VK_KHR_xcb_surface
[ERR] yuv (G8_B8R8_2PLANE_420) not supported!
[ERR] init vulkan failed
[ERR] failed to init gui/swapchain
```
I've tried to run vkdt on a fresh WSL2 Ubuntu installation on Windows 11. [I've got the binary from Suse](https://software.opensuse.org/download.html?project=graphics%3Adarktable%3Amaster&package=vkdt).

~~My monitor is currently running as YUV 4:2:0[^1], so the crash message does make sense.~~
EDIT: I've double checked with RGB / without chroma subsampling and that didn't change anything.
The GPU is an old GTX 960, I guess maybe it doesn't support the needed Vulkan extensions / texture formats

[^1]: Yeah I know that's terrible for image editing

**Comment by hanatos** [comment]
hi,

this is unrelated to your screen setup. yuv textures are used to accelerate handling of some webcams. i should probably make this thing optional, although gpuinfo.org indicates that your gpu should in theory support the texture format (not sure about the exact features in detail). also possible that something between the cracks of windows and the subsystem layer doesn't report the right vulkan features, i will never find out.

i really don't know much about windows but i was hoping that filling in [a few gaps like here](https://github.com/hanatos/vkdt/blob/master/src/core/fs.h#L128) should make a more native/msys2 build possible for this platform.

**Comment by hanatos** [comment]
i see no way i could work on this. either it's a translation layer problem or the gpu is too old. anyways a native windows binary will likely be better.
